/* Autogenerated by png2wx.pl on Sat Dec 28 09:03:54 2013 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

#include <wx/filename.h>
#include <wx/mstream.h>

extern void initialize_images(void);

extern wxBitmap *_img_statusbar;

#ifdef PLUGIN_USE_SVG
extern wxString _svg_statusbar;
extern wxString _svg_statusbar_rollover;
extern wxString _svg_statusbar_toggled;
#endif


#endif /* ICONS_H */
